#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# polkit agent
if [[ ! 'pidof polkit-gnome-authentication-agent-1' ]];then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

variety -n &
nm-applet --indicator &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

${SCRIPTSDIR}/statusbar portal